let datas = [
    {
        rollNo:1001,
        name:'Akshat Jain',
        dstl:48,
        coa:44,
        ds:47,
        cs:38,
        de:45,
        tc:39,

    },
    {
        rollNo:1002,
        name:'Ansh Singhal',
        dstl:42,
        coa:42,
        ds:45,
        cs:35,
        de:42,
        tc:39,

    },
    {
        rollNo:1003,
        name:'Arin',
        dstl:42,
        coa:42,
        ds:45,
        cs:35,
        de:42,
        tc:39,
    },
    {
        rollNo:1004,
        name:'Arish',
        dstl:42,
        coa:42,
        ds:45,
        cs:35,
        de:42,
        tc:39,
    },
    {
        rollNo:1005,
        name:'Aayush Tyagi',
        dstl:42,
        coa:42,
        ds:45,
        cs:35,
        de:42,
        tc:39,
    },
    {
        rollNo:1006,
        name:'Amar Sharma',
        dstl:42,
        coa:42,
        ds:45,
        cs:35,
        de:42,
        tc:39,
    },
    {
        rollNo:1007,
        name:'Rahul',
        dstl:22,
        coa:12,
        ds:45,
        cs:25,
        de:32,
        tc:39,
    },

]